Authorization
ardium-pl/SQL-translator pull request #4
Opened 2024-10-10 15:25 UTC by 22skowron

2024-10-10 17:52 UTC, joker876 requested changes

2024-10-10 17:52 UTC, joker876 commented on client/src/app/components/results-grid/results-grid.component.ts
> +    return colDefs;
najlepiej od razu dać `return columnNames.map(........`

2024-10-10 17:52 UTC, joker876 commented on client/src/app/pages/main-page/main-page.component.html
> +  "
Utworzyć dedykowaną metodę dla przycisku. Jeśli trzeba wykonać więcej niż jedną rzecz przy kliknięciu to zawsze tworzymy metodę.

2024-10-10 17:52 UTC, joker876 commented on client/src/app/pages/main-page/main-page.component.ts
> +    zapytanieInput: new FormControl(this.dataFetchingService.zapytanieInput()),
Tutaj tak samo: `zapytanie` zamiast `zapytanieInput` (a swoją drogą to powinno być po angielsku, skoro reszta kodu też jest po angielsku)

2024-10-10 17:52 UTC, joker876 commented on client/src/app/services/auth.service.ts
> +  }
Domyślam się że nie wiedziałeś że takie coś istnieje (bo nie ma dokumentacji, muszę kiedyś w końcu zrobić...), ale biblioteka `@ardium-ui/devkit` udostępnia coś takiego:

![image](https://github.com/user-attachments/assets/62fee4bd-984a-4c2c-b9cf-42b6fbf26615)

To cudo automatycznie zapisuje/odczytuje wartość z localStorage/czegoś innego.

Dokumentacji online może i nie ma, ale jak najedziesz na `persistentSignal` to wyświetli ci się opis

2024-10-10 17:52 UTC, joker876 commented on client/src/app/services/data-fetching.service.ts
> +              default:
Jeśli napisałbyś kolejnego requesta, tam też dałbyś ten sam kod co tutaj? A co jak zrobisz 10 requestów, wszędzie kopiuj-wklej ten sam kod?
 
 Część kodu odpowiedzialną za sprawdzanie, czy error dotyczy JWT powinna być przeniesiona do interceptora.

2024-10-10 17:52 UTC, joker876 commented on client/src/app/utils/exampleValues.ts
> +    handlowiec: 'Nowak Mciej (563)',
zmienić na angielską nazwę kolumny

2024-10-10 17:52 UTC, joker876 commented on server/Utils/middleware.js
> +  });
Najlepiej jakby zamiast `message` zwracano w obiekcie np. `errorCode`, z wartościami np. `NO_TOKEN_ERR` oraz `INVALID_TOKEN_ERR`. Mapowanie kodu na wiadomość powinno odbywać się na froncie.

2024-10-10 17:52 UTC, joker876 commented on server/index.js
>  dotenv.config();
```ts
import dotenv from "dotenv";

dotenv.config()
```

można zastąpić 

```ts
import "dotenv/config";
```

2024-10-10 17:52 UTC, joker876 commented on server/index.js
> +    res.status(401).json({ status: "error", message: "Invalid password" });
tutaj też `message` -> `errorCode`

2024-10-10 17:52 UTC, joker876 commented on server/index.js
> +      .json({ status: "success", message: "Logged in successfully." });
Tutaj z kolei `message` w ogóle nie potrzebny

2024-10-10 17:52 UTC, joker876 commented on server/index.js
> +    .json({ status: "success", message: "Logged out successfully." });
Tu też `message` niepotrzebny

2024-10-10 17:52 UTC, joker876 commented on server/index.js
> +    res.status(400).json({ status: "error", message: "No query provided." });
`message` -> `errorCode`

2024-10-10 17:52 UTC, joker876 commented on server/index.js
>          message: "An error occured while processing the request.",
`message` -> `errorCode`

2024-10-10 17:52 UTC, joker876 commented on server/index.js
>          message:
`message` niepotrzebny

2024-10-10 17:52 UTC, joker876 commented on server/index.js
>          message: "Database error. Failed to execute the SQL query.",
`message` -> `errrorCode`

2024-10-10 17:52 UTC, joker876 commented on server/index.js
>          message: "An error occured while processing the request.",
`message` -> `errrorCode`

2024-10-10 17:52 UTC, joker876 commented on server/index.js
>          message:
Swoją drogą dlaczego status error ma status 200? Tu powinno być 400

2024-10-10 17:52 UTC, joker876 commented on server/index.js
> +      message: "An error occured while processing the request.",
`message` -> `errrorCode`

2024-10-10 17:52 UTC, joker876 commented on server/package.json
`nodemon` powinien być wewnątrz `devDependencies`. Nie ma potrzeby, żeby serwer hostingowy pobierał nodemona, jeśli nie będzie go używał

```
npm uninstall nodemon
npm i -D nodemon
```

2024-10-10 17:52 UTC, joker876 commented on server/index.js
Handling requestów przenieść do własnych plików. Każdy handler powinien mieć najlepiej własny plik, a na koniec powinny być zgrupowane na razem w jednym routerze. Najlepiej też jakby `login` i `logout` były podpięte pod `authRouter` (ze ścieżką `/auth`, a więc ścieżki wynikowe będą np. `/auth/login`), a pozostałe pod osobny router

2024-10-10 19:27 UTC, 22skowron commented on client/src/app/utils/exampleValues.ts
> +    handlowiec: 'Nowak Mciej (563)',
Nazwy kolumn jak i dane w Ag Gridzie będą generowane dynamicznie na podstawie tego co przyjdzie z backendu. W MySQL bazie danych wszystko (łącznie z nazwami kolumn) jest po polsku i wszystko też ma być po polsku wyświetlane na front'cie.

2024-10-10 19:29 UTC, 22skowron commented on client/src/app/services/auth.service.ts
> +  }
Nie no hindusi z jutuba uczli, żeby robić tak jak jest zaimplementowane, nie będę już tego zmieniał.

2024-10-10 19:37 UTC, 22skowron commented on client/src/app/components/button/button.component.ts
> +  readonly type = input<string>('text');
type any

2024-10-11 13:14 UTC, joker876 commented on client/src/app/services/auth.service.ts
> +  }
To że ci Hindus z jutuba coś powiedział to nie znaczy że to jest prawda objawiona i jak można coś zrobić lepiej to należy skorzystać z takiej opcji, tym bardziej że nie musisz nic dodatkowego kodować, tylko użyć gotowej i sprawdzonej rzeczy

2024-10-11 13:16 UTC, joker876 commented on client/src/app/components/button/button.component.ts
> +  readonly type = input<string>('text');
poprawa tego typu zajęłaby mi mniej niż napisanie tego komentarza, więc nie kombinuj nic z `any` i zrób jak mówiłem

2024-10-11 13:17 UTC, joker876 commented on client/src/app/utils/exampleValues.ts
> +    handlowiec: 'Nowak Mciej (563)',
Dobra, skoro to i tak są tylko przykładowe dane to niech zostanie jak jest

2024-10-11 18:49 UTC, 22skowron commented on client/src/app/components/card/card-input/card-input.component.scss
> +  @include m3-body-large;
Ja sobie je specjalnie dawałem na środku, oddzielało mi style, które są zdefiniowane głównie przy użyciu bezpośrednio wartości i te zdefiniwoane przy użyciu CSS variables.

2024-10-11 21:19 UTC, joker876 requested changes

2024-10-11 21:19 UTC, joker876 commented on server/API/authorizationRouter.js
> +      .status(401)
tutaj powinien być status 400

2024-10-11 21:52 UTC, joker876 commented on server/Utils/middleware.js
> +  });
Nie chodziło mi o samo zamienienie nazwy wysyłanego pola. Napisałem konkretnie że wartość tego pola nie ma być wiadomością, a raczej kodem (podałem nawet przykłady).

Czemu nie wiadomość? Co by się stało, jeśli jakiś inny programista postanowi dopisać do wiadomości kropkę na końcu? A no wywali się tłumaczenie błędów na froncie.

2024-10-11 21:54 UTC, joker876 commented on server/index.js
>  dotenv.config();
Nie poprawione

2024-10-14 11:51 UTC, 22skowron commented on server/API/authorizationRouter.js
> +      .status(401)
Nie powinien.

> **401 Unauthorized**
Similar to 403 Forbidden, but specifically for use when authentication is required and has failed or has not yet been provided. 401 semantically means "unauthenticated", the user does not have valid authentication credentials for the target resource.
[https://en.wikipedia.org/wiki/List_of_HTTP_status_codes](url)

2024-10-15 21:32 UTC, joker876 approved these changes

2024-10-15 21:32 UTC, merged